# Generated by Django 3.2.9 on 2022-03-15 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('activo', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n1', models.DecimalField(decimal_places=2, max_digits=4)),
                ('n2', models.DecimalField(decimal_places=2, max_digits=4)),
                ('n3', models.DecimalField(decimal_places=2, max_digits=4)),
                ('activo', models.CharField(max_length=1)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personas.alumno')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personas.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=15)),
                ('campo', models.CharField(max_length=15)),
                ('valor_old', models.CharField(max_length=200)),
                ('valor_new', models.CharField(max_length=200)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
