# Generated by Django 3.2.9 on 2022-03-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auditoria_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
