# Generated by Django 3.2.9 on 2022-03-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_auto_20220315_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='ano',
            field=models.DecimalField(decimal_places=0, default=2022, max_digits=4),
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('alumno', 'asignatura', 'ano')},
        ),
    ]
